baseURL: https://jenniferschepke.com # todo: change site url.
title: Jennifer Schepke # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  logo: logo.png # todo: add your custom logo to static/
  subtitle: Jennifer Schepke is an artist and illustrator from Michigan # todo: change default subtitle for your website.
  copyright: All rights reserved. # todo: set your copyright type.
  author: Jennifer Schepke # todo: set your full name.
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        nature: 4
        sketchbook: 6
        people: 2
        default: 3
      mobile:
        default: 2
        sketchbook: 3
        people: 1
  socials:
    # todo: change these links.
    - icon: 'x'
      url: 'https://twitter.com/jenniferschepke'
      landing: true
    - icon: 'rumble'
      url: 'https://rumble.com/c/c-5377345'
      landing: true
    - icon: 'kofi'
      url: 'https://ko-fi.com/jenniferschepke/shop'
      landing: true
    - icon: 'tutanota'
      url: 'mailto:jenniferschepke@tuta.com'
      landing: true
  homepage: "/work" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - about
    - sketchbook
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: true # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: false

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: about + contact
      url: /about/
      weight: 2
    - name: shop
      url: https://ko-fi.com/jenniferschepke/shop/
      weight: 3
    - name: videos
      url: https://www.tiktok.com/@jenniferschepke
      weight: 4
